services:
  - type: web
    name: invoice-ai-backend
    env: docker
    plan: free

    rootDir: backend
    dockerfilePath: ./Dockerfile

    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false